# Generated by Django 4.1.5 on 2023-01-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DividendHistory',
            fields=[
                ('stock_symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('adj_dividend', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dividend', models.DecimalField(decimal_places=3, max_digits=10)),
                ('record_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('declaration_date', models.DateField()),
            ],
        ),
    ]
